theme = "bad-wolf"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 21

[[block]]
block = "battery"
device = "BAT1"
driver = "sysfs"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}° avg"

[[block]]
block = "music"
player = "cmus"
buttons = ["play", "next"]

[[block]]
block = "sound"

[[block]]
block = "backlight"

[[block]]
block = "net"
device = "wlp0s20f3"
ssid = true
signal_strength = true
ip = true
interval = 5
use_bits = false

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
